
package client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T21:47:27.348-06:00
 * Generated source version: 2.7.6
 * 
 */
public final class LunchService_LunchServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service/", "LunchService");

    private LunchService_LunchServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LunchService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LunchService_Service ss = new LunchService_Service(wsdlURL, SERVICE_NAME);
        LunchService port = ss.getLunchServiceImplPort();  
        
        System.out.println("Invoking getMenu...");
        client.Service _getMenu__return = port.getMenu();

        for(int i = 0; i < _getMenu__return.getRestaurants().size(); i++) {
            client.Restaurant res = _getMenu__return.getRestaurants().get(i);
            System.out.println(String.format("%d: %s - %s", i + 1, res.getName(), res.getDescription()));
            for(int j = 0; j < res.getMeals().size(); j++) {
                client.Meal m = res.getMeals().get(j);
                System.out.println(String.format("%f - %s - %s", m.getPrice(), m.getName(), m.getDescription()));
            }
        }

        System.out.println("Please enter the ordinal of the restaurant you'd like to order from:");
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        int resOrd = Integer.valueOf(reader.readLine()) - 1;
        System.out.println("Please enter the ordinal of the meal you'd like to order");
        int mealOrd = Integer.valueOf(reader.readLine()) - 1;
        System.out.println("Please enter your name");
        String name = reader.readLine();

        System.out.println("Invoking orderMeal...");
        port.orderMeal(name, mealOrd, resOrd);
    }

}
