package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-10T22:48:57.286-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://localhost/lunch", name = "LunchService")
@XmlSeeAlso({ObjectFactory.class})
public interface LunchService {

    @WebResult(name = "service", targetNamespace = "")
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://localhost/lunch", className = "client.GetMenu")
    @WebMethod
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://localhost/lunch", className = "client.GetMenuResponse")
    public client.Service getMenu();

    @RequestWrapper(localName = "orderMeal", targetNamespace = "http://localhost/lunch", className = "client.OrderMeal")
    @WebMethod
    @ResponseWrapper(localName = "orderMealResponse", targetNamespace = "http://localhost/lunch", className = "client.OrderMealResponse")
    public void orderMeal(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "mealId", targetNamespace = "")
        java.lang.Integer mealId,
        @WebParam(name = "restaurantId", targetNamespace = "")
        java.lang.Integer restaurantId
    );
}
